# Generated by Django 5.1.4 on 2025-03-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='edited_image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
